{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Tower 3",
      "fix_state": "Under investigation",
      "package_name": "python3-PyYAML",
      "cpe": "cpe:/a:redhat:ansible_tower:3"
    },
    {
      "product_name": "Red Hat Ansible Tower 3",
      "fix_state": "Under investigation",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:ansible_tower:3"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Under investigation",
      "package_name": "PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python27:2.7/PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python38:3.8/PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Under investigation",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Under investigation",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Under investigation",
      "package_name": "python-PyYAML",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Under investigation",
      "package_name": "python27-PyYAML",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Under investigation",
      "package_name": "rh-python36-PyYAML",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Under investigation",
      "package_name": "rh-python38-PyYAML",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-07-22T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-14343 PyYAML: incomplete fix for CVE-2020-1747",
    "id": "1860466",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "9.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-14343",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}