{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Under investigation",
      "package_name": "freerdp",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "freerdp",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "freerdp",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2020-03-30T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-11046 freerdp: out of bounds seek in update_read_synchronize function could lead out of bounds read",
    "id": "1835403",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1835403"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:C/C:L/I:L/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-119-\u003eCWE-125",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-11046",
  "document_distribution": "",
  "details": [
    "In FreeRDP after 1.0 and before 2.0.0, there is a stream out-of-bounds seek in update_read_synchronize that could lead to a later out-of-bounds read."
  ],
  "references": null
}