{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2020-06-25T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-10177 python-pillow: multiple out-of-bounds reads in libImaging/FliDecode.c",
    "id": "1852824",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1852824"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "4.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:H/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-10177",
  "document_distribution": "",
  "details": [
    "Pillow before 6.2.3 and 7.x before 7.0.1 has multiple out-of-bounds reads in libImaging/FliDecode.c."
  ],
  "references": null
}