{
  "Severity": "MODERATE",
  "UpdatedAt": "2019-11-27T02:25:59Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "typed-ast"
  },
  "Advisory": {
    "DatabaseId": 1809,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLTd4eHYtd3B4ai1teDV2",
    "GhsaId": "GHSA-7xxv-wpxj-mx5v",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2019-19275"
      },
      {
        "Url": "https://github.com/advisories/GHSA-7xxv-wpxj-mx5v"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-7xxv-wpxj-mx5v"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2019-19275"
      }
    ],
    "Description": "typed_ast 1.3.0 and 1.3.1 has an ast_for_arguments out-of-bounds read. An attacker with the ability to cause a Python interpreter to parse Python source (but not necessarily execute it) may be able to crash the interpreter process. This could be a concern, for example, in a web-based service that parses (but does not execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2019-12-02T18:03:09Z",
    "Severity": "MODERATE",
    "Summary": "Out-of-bounds read in typed-ast and cpython may allow an attacker to crash the interpreter process (ast_for_arguments case).",
    "UpdatedAt": "2019-12-20T02:10:20Z",
    "WithdrawnAt": ""
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "1.4.0"
      },
      "VulnerableVersionRange": "\u003e= 1.3.0, \u003c= 1.3.1"
    }
  ]
}